apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Post-renderer for Helm chart
# ArgoCD pipes Helm output through this kustomization to apply labels

# Include common labels component
components:
- ../../components/common-labels

# Add staging-specific label
labels:
- pairs:
    zumba.io/environment: stage
  includeSelectors: false
  includeTemplates: false
