apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "n8n-stack.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "n8n-stack.postgres.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
