apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Post-renderer for Helm chart
# Applies labels to all Helm-generated resources

# Include common labels component
components:
- ../../components/common-labels

# Resources will be piped in from Helm
resources: []

# Add production-specific label
labels:
- pairs:
    zumba.io/environment: prod
  includeSelectors: false
  includeTemplates: false
