apiVersion: v1
kind: Service
metadata:
  name: {{ include "zumba.fullname" . }}-postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "zumba.postgres.labels" . | nindent 4 }}
spec:
  type: {{ if .Values.postgres.externalAccess.enabled }}{{ .Values.postgres.externalAccess.type }}{{ else }}{{ .Values.postgres.service.type }}{{ end }}
  {{- if and .Values.postgres.externalAccess.enabled .Values.postgres.externalAccess.loadBalancerIP }}
  loadBalancerIP: {{ .Values.postgres.externalAccess.loadBalancerIP }}
  {{- end }}
  {{- if .Values.postgres.externalAccess.enabled }}
  externalTrafficPolicy: Local
  {{- end }}
  ports:
    - port: {{ if .Values.postgres.externalAccess.enabled }}{{ .Values.postgres.externalAccess.port }}{{ else }}{{ .Values.postgres.service.port }}{{ end }}
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    {{- include "zumba.postgres.selectorLabels" . | nindent 4 }}
