apiVersion: v1
kind: Service
metadata:
  name: {{ include "zumba.fullname" . }}-evolution-api
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "zumba.evolutionApi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.evolutionApi.service.type }}
  ports:
    - port: {{ .Values.evolutionApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zumba.evolutionApi.selectorLabels" . | nindent 4 }}
