{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "zumba-stack.fullname" . }}-n8n
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "zumba-stack.n8n.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ include "zumba-stack.fullname" . }}-n8n
          port: {{ .Values.n8n.service.port }}
{{- end }}
