apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n-stack.fullname" . }}-n8n
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "n8n-stack.n8n.labels" . | nindent 4 }}
spec:
  type: {{ .Values.n8n.service.type }}
  ports:
    - port: {{ .Values.n8n.service.port }}
      targetPort: 5678
      protocol: TCP
      name: http
  selector:
    {{- include "n8n-stack.n8n.selectorLabels" . | nindent 4 }}
